// default package
// Generated 2018/8/31 ?? 11:02:32 by Hibernate Tools 3.4.0.CR1
package com.lifung.dao;
import java.util.Date;

/**
 * Facility generated by hbm2java
 */
public class Facility implements java.io.Serializable {

	private String facility;
	private String descr;
	private String userDefine01;
	private String userDefine02;
	private String userDefine03;
	private String userDefine04;
	private String userDefine05;
	private String userDefine06;
	private String userDefine07;
	private String userDefine08;
	private String userDefine09;
	private String userDefine10;
	private String userDefine11;
	private String userDefine12;
	private String userDefine13;
	private String userDefine14;
	private String userDefine15;
	private String userDefine16;
	private String userDefine17;
	private String userDefine18;
	private String userDefine19;
	private String userDefine20;
	private String addwho;
	private Date addDate;
	private String editWho;
	private Date editDate;
	private String tmsInterface;
	private String address1;
	private String address2;
	private String address3;
	private String address4;
	private String city;
	private String state;
	private String zip;
	private String country;
	private String isocntryCode;
	private String contact1;
	private String contact2;
	private String phone1;
	private String phone2;
	private String fax1;
	private String fax2;
	private String email1;
	private String email2;
	private String type;
	private int sqFeet;
	private String longitude;
	private String latitude;
	private String timeZone;
	private Integer noOfDoors;
	private String leaseType;
	private String operationHours;
	private String facilityFor;

	public Facility() {
	}

	public Facility(String facility, String descr, String addwho, Date addDate, String editWho, Date editDate,
			String type, int sqFeet) {
		this.facility = facility;
		this.descr = descr;
		this.addwho = addwho;
		this.addDate = addDate;
		this.editWho = editWho;
		this.editDate = editDate;
		this.type = type;
		this.sqFeet = sqFeet;
	}

	public Facility(String facility, String descr, String userDefine01, String userDefine02, String userDefine03,
			String userDefine04, String userDefine05, String userDefine06, String userDefine07, String userDefine08,
			String userDefine09, String userDefine10, String userDefine11, String userDefine12, String userDefine13,
			String userDefine14, String userDefine15, String userDefine16, String userDefine17, String userDefine18,
			String userDefine19, String userDefine20, String addwho, Date addDate, String editWho, Date editDate,
			String tmsInterface, String address1, String address2, String address3, String address4, String city,
			String state, String zip, String country, String isocntryCode, String contact1, String contact2,
			String phone1, String phone2, String fax1, String fax2, String email1, String email2, String type,
			int sqFeet, String longitude, String latitude, String timeZone, Integer noOfDoors, String leaseType,
			String operationHours, String facilityFor) {
		this.facility = facility;
		this.descr = descr;
		this.userDefine01 = userDefine01;
		this.userDefine02 = userDefine02;
		this.userDefine03 = userDefine03;
		this.userDefine04 = userDefine04;
		this.userDefine05 = userDefine05;
		this.userDefine06 = userDefine06;
		this.userDefine07 = userDefine07;
		this.userDefine08 = userDefine08;
		this.userDefine09 = userDefine09;
		this.userDefine10 = userDefine10;
		this.userDefine11 = userDefine11;
		this.userDefine12 = userDefine12;
		this.userDefine13 = userDefine13;
		this.userDefine14 = userDefine14;
		this.userDefine15 = userDefine15;
		this.userDefine16 = userDefine16;
		this.userDefine17 = userDefine17;
		this.userDefine18 = userDefine18;
		this.userDefine19 = userDefine19;
		this.userDefine20 = userDefine20;
		this.addwho = addwho;
		this.addDate = addDate;
		this.editWho = editWho;
		this.editDate = editDate;
		this.tmsInterface = tmsInterface;
		this.address1 = address1;
		this.address2 = address2;
		this.address3 = address3;
		this.address4 = address4;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.country = country;
		this.isocntryCode = isocntryCode;
		this.contact1 = contact1;
		this.contact2 = contact2;
		this.phone1 = phone1;
		this.phone2 = phone2;
		this.fax1 = fax1;
		this.fax2 = fax2;
		this.email1 = email1;
		this.email2 = email2;
		this.type = type;
		this.sqFeet = sqFeet;
		this.longitude = longitude;
		this.latitude = latitude;
		this.timeZone = timeZone;
		this.noOfDoors = noOfDoors;
		this.leaseType = leaseType;
		this.operationHours = operationHours;
		this.facilityFor = facilityFor;
	}

	public String getFacility() {
		return this.facility;
	}

	public void setFacility(String facility) {
		this.facility = facility;
	}

	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	public String getUserDefine01() {
		return this.userDefine01;
	}

	public void setUserDefine01(String userDefine01) {
		this.userDefine01 = userDefine01;
	}

	public String getUserDefine02() {
		return this.userDefine02;
	}

	public void setUserDefine02(String userDefine02) {
		this.userDefine02 = userDefine02;
	}

	public String getUserDefine03() {
		return this.userDefine03;
	}

	public void setUserDefine03(String userDefine03) {
		this.userDefine03 = userDefine03;
	}

	public String getUserDefine04() {
		return this.userDefine04;
	}

	public void setUserDefine04(String userDefine04) {
		this.userDefine04 = userDefine04;
	}

	public String getUserDefine05() {
		return this.userDefine05;
	}

	public void setUserDefine05(String userDefine05) {
		this.userDefine05 = userDefine05;
	}

	public String getUserDefine06() {
		return this.userDefine06;
	}

	public void setUserDefine06(String userDefine06) {
		this.userDefine06 = userDefine06;
	}

	public String getUserDefine07() {
		return this.userDefine07;
	}

	public void setUserDefine07(String userDefine07) {
		this.userDefine07 = userDefine07;
	}

	public String getUserDefine08() {
		return this.userDefine08;
	}

	public void setUserDefine08(String userDefine08) {
		this.userDefine08 = userDefine08;
	}

	public String getUserDefine09() {
		return this.userDefine09;
	}

	public void setUserDefine09(String userDefine09) {
		this.userDefine09 = userDefine09;
	}

	public String getUserDefine10() {
		return this.userDefine10;
	}

	public void setUserDefine10(String userDefine10) {
		this.userDefine10 = userDefine10;
	}

	public String getUserDefine11() {
		return this.userDefine11;
	}

	public void setUserDefine11(String userDefine11) {
		this.userDefine11 = userDefine11;
	}

	public String getUserDefine12() {
		return this.userDefine12;
	}

	public void setUserDefine12(String userDefine12) {
		this.userDefine12 = userDefine12;
	}

	public String getUserDefine13() {
		return this.userDefine13;
	}

	public void setUserDefine13(String userDefine13) {
		this.userDefine13 = userDefine13;
	}

	public String getUserDefine14() {
		return this.userDefine14;
	}

	public void setUserDefine14(String userDefine14) {
		this.userDefine14 = userDefine14;
	}

	public String getUserDefine15() {
		return this.userDefine15;
	}

	public void setUserDefine15(String userDefine15) {
		this.userDefine15 = userDefine15;
	}

	public String getUserDefine16() {
		return this.userDefine16;
	}

	public void setUserDefine16(String userDefine16) {
		this.userDefine16 = userDefine16;
	}

	public String getUserDefine17() {
		return this.userDefine17;
	}

	public void setUserDefine17(String userDefine17) {
		this.userDefine17 = userDefine17;
	}

	public String getUserDefine18() {
		return this.userDefine18;
	}

	public void setUserDefine18(String userDefine18) {
		this.userDefine18 = userDefine18;
	}

	public String getUserDefine19() {
		return this.userDefine19;
	}

	public void setUserDefine19(String userDefine19) {
		this.userDefine19 = userDefine19;
	}

	public String getUserDefine20() {
		return this.userDefine20;
	}

	public void setUserDefine20(String userDefine20) {
		this.userDefine20 = userDefine20;
	}

	public String getAddwho() {
		return this.addwho;
	}

	public void setAddwho(String addwho) {
		this.addwho = addwho;
	}

	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	public String getEditWho() {
		return this.editWho;
	}

	public void setEditWho(String editWho) {
		this.editWho = editWho;
	}

	public Date getEditDate() {
		return this.editDate;
	}

	public void setEditDate(Date editDate) {
		this.editDate = editDate;
	}

	public String getTmsInterface() {
		return this.tmsInterface;
	}

	public void setTmsInterface(String tmsInterface) {
		this.tmsInterface = tmsInterface;
	}

	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getAddress3() {
		return this.address3;
	}

	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	public String getAddress4() {
		return this.address4;
	}

	public void setAddress4(String address4) {
		this.address4 = address4;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getIsocntryCode() {
		return this.isocntryCode;
	}

	public void setIsocntryCode(String isocntryCode) {
		this.isocntryCode = isocntryCode;
	}

	public String getContact1() {
		return this.contact1;
	}

	public void setContact1(String contact1) {
		this.contact1 = contact1;
	}

	public String getContact2() {
		return this.contact2;
	}

	public void setContact2(String contact2) {
		this.contact2 = contact2;
	}

	public String getPhone1() {
		return this.phone1;
	}

	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	public String getFax1() {
		return this.fax1;
	}

	public void setFax1(String fax1) {
		this.fax1 = fax1;
	}

	public String getFax2() {
		return this.fax2;
	}

	public void setFax2(String fax2) {
		this.fax2 = fax2;
	}

	public String getEmail1() {
		return this.email1;
	}

	public void setEmail1(String email1) {
		this.email1 = email1;
	}

	public String getEmail2() {
		return this.email2;
	}

	public void setEmail2(String email2) {
		this.email2 = email2;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getSqFeet() {
		return this.sqFeet;
	}

	public void setSqFeet(int sqFeet) {
		this.sqFeet = sqFeet;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getTimeZone() {
		return this.timeZone;
	}

	public void setTimeZone(String timeZone) {
		this.timeZone = timeZone;
	}

	public Integer getNoOfDoors() {
		return this.noOfDoors;
	}

	public void setNoOfDoors(Integer noOfDoors) {
		this.noOfDoors = noOfDoors;
	}

	public String getLeaseType() {
		return this.leaseType;
	}

	public void setLeaseType(String leaseType) {
		this.leaseType = leaseType;
	}

	public String getOperationHours() {
		return this.operationHours;
	}

	public void setOperationHours(String operationHours) {
		this.operationHours = operationHours;
	}

	public String getFacilityFor() {
		return this.facilityFor;
	}

	public void setFacilityFor(String facilityFor) {
		this.facilityFor = facilityFor;
	}

}
