// default package
// Generated 2018/11/19 ?? 08:35:42 by Hibernate Tools 3.4.0.CR1
package com.lifung.dao;
import java.util.Date;

/**
 * ForecastId generated by hbm2java
 */
public class ForecastId implements java.io.Serializable {

	private Date f_date;
	private Long qty;
	private String storerkey;

	public ForecastId() {
	}

	public ForecastId(Date f_date, Long qty, String storerkey) {
		this.f_date = f_date;
		this.qty = qty;
		this.storerkey = storerkey;
	}

	 

	 

	 
	public Date getF_date() {
		return f_date;
	}

	public void setF_date(Date f_date) {
		this.f_date = f_date;
	}

	public Long getQty() {
		return this.qty;
	}

	public void setQty(Long qty) {
		this.qty = qty;
	}

	public String getStorerkey() {
		return this.storerkey;
	}

	public void setStorerkey(String storerkey) {
		this.storerkey = storerkey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ForecastId))
			return false;
		ForecastId castOther = (ForecastId) other;

		return ((this.getF_date() == castOther.getF_date()) || (this.getF_date() != null && castOther.getF_date() != null
				&& this.getF_date().equals(castOther.getF_date())))
				&& ((this.getQty() == castOther.getQty()) || (this.getQty() != null && castOther.getQty() != null
						&& this.getQty().equals(castOther.getQty())))
				&& ((this.getStorerkey() == castOther.getStorerkey()) || (this.getStorerkey() != null
						&& castOther.getStorerkey() != null && this.getStorerkey().equals(castOther.getStorerkey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getF_date() == null ? 0 : this.getF_date().hashCode());
		result = 37 * result + (getQty() == null ? 0 : this.getQty().hashCode());
		result = 37 * result + (getStorerkey() == null ? 0 : this.getStorerkey().hashCode());
		return result;
	}

}
