// default package
// Generated 2018/11/19 ?? 08:35:42 by Hibernate Tools 3.4.0.CR1
package com.lifung.dao;
/**
 * Forecast generated by hbm2java
 */
public class Forecast implements java.io.Serializable {

	private ForecastId id;

	public Forecast() {
	}

	public Forecast(ForecastId id) {
		this.id = id;
	}

	public ForecastId getId() {
		return this.id;
	}

	public void setId(ForecastId id) {
		this.id = id;
	}

}
