// default package
// Generated 2018/12/5 ?? 03:18:25 by Hibernate Tools 3.4.0.CR1
package com.lifung.dao;
import java.util.Date;

/**
 * InLine generated by hbm2java
 */
public class InLine implements java.io.Serializable {

	private int seqNo;
	private int fileKey;
	private String dataStream;
	private Integer attachmentId;
	private String fileName;
	private char status;
	private String lineText;
	private String errMsg;
	private Date addDate;
	private Date editDate;
	private String lineTextUnicode;
	private String refKey1;
	private String refKey2;
	private String refKey4;
	private String refKey5;
	private String refKey3;
	private String archiveCop;
	private String trafficCop;
	private String lineTextOriginal;

	public InLine() {
	}

	public InLine(int seqNo, int fileKey, String dataStream, char status, Date addDate, Date editDate, String refKey1,
			String refKey2, String refKey4, String refKey5, String refKey3) {
		this.seqNo = seqNo;
		this.fileKey = fileKey;
		this.dataStream = dataStream;
		this.status = status;
		this.addDate = addDate;
		this.editDate = editDate;
		this.refKey1 = refKey1;
		this.refKey2 = refKey2;
		this.refKey4 = refKey4;
		this.refKey5 = refKey5;
		this.refKey3 = refKey3;
	}

	public InLine(int seqNo, int fileKey, String dataStream, Integer attachmentId, String fileName, char status,
			String lineText, String errMsg, Date addDate, Date editDate, String lineTextUnicode, String refKey1,
			String refKey2, String refKey4, String refKey5, String refKey3, String archiveCop, String trafficCop,
			String lineTextOriginal) {
		this.seqNo = seqNo;
		this.fileKey = fileKey;
		this.dataStream = dataStream;
		this.attachmentId = attachmentId;
		this.fileName = fileName;
		this.status = status;
		this.lineText = lineText;
		this.errMsg = errMsg;
		this.addDate = addDate;
		this.editDate = editDate;
		this.lineTextUnicode = lineTextUnicode;
		this.refKey1 = refKey1;
		this.refKey2 = refKey2;
		this.refKey4 = refKey4;
		this.refKey5 = refKey5;
		this.refKey3 = refKey3;
		this.archiveCop = archiveCop;
		this.trafficCop = trafficCop;
		this.lineTextOriginal = lineTextOriginal;
	}

	public int getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(int seqNo) {
		this.seqNo = seqNo;
	}

	public int getFileKey() {
		return this.fileKey;
	}

	public void setFileKey(int fileKey) {
		this.fileKey = fileKey;
	}

	public String getDataStream() {
		return this.dataStream;
	}

	public void setDataStream(String dataStream) {
		this.dataStream = dataStream;
	}

	public Integer getAttachmentId() {
		return this.attachmentId;
	}

	public void setAttachmentId(Integer attachmentId) {
		this.attachmentId = attachmentId;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	public String getLineText() {
		return this.lineText;
	}

	public void setLineText(String lineText) {
		this.lineText = lineText;
	}

	public String getErrMsg() {
		return this.errMsg;
	}

	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;
	}

	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	public Date getEditDate() {
		return this.editDate;
	}

	public void setEditDate(Date editDate) {
		this.editDate = editDate;
	}

	public String getLineTextUnicode() {
		return this.lineTextUnicode;
	}

	public void setLineTextUnicode(String lineTextUnicode) {
		this.lineTextUnicode = lineTextUnicode;
	}

	public String getRefKey1() {
		return this.refKey1;
	}

	public void setRefKey1(String refKey1) {
		this.refKey1 = refKey1;
	}

	public String getRefKey2() {
		return this.refKey2;
	}

	public void setRefKey2(String refKey2) {
		this.refKey2 = refKey2;
	}

	public String getRefKey4() {
		return this.refKey4;
	}

	public void setRefKey4(String refKey4) {
		this.refKey4 = refKey4;
	}

	public String getRefKey5() {
		return this.refKey5;
	}

	public void setRefKey5(String refKey5) {
		this.refKey5 = refKey5;
	}

	public String getRefKey3() {
		return this.refKey3;
	}

	public void setRefKey3(String refKey3) {
		this.refKey3 = refKey3;
	}

	public String getArchiveCop() {
		return this.archiveCop;
	}

	public void setArchiveCop(String archiveCop) {
		this.archiveCop = archiveCop;
	}

	public String getTrafficCop() {
		return this.trafficCop;
	}

	public void setTrafficCop(String trafficCop) {
		this.trafficCop = trafficCop;
	}

	public String getLineTextOriginal() {
		return this.lineTextOriginal;
	}

	public void setLineTextOriginal(String lineTextOriginal) {
		this.lineTextOriginal = lineTextOriginal;
	}

}
