// default package
// Generated 2018/4/19 ?? 06:11:16 by Hibernate Tools 3.4.0.CR1
package com.lifung.dao;
/**
 * ItfConfigId generated by hbm2java
 */
public class ItfConfigId implements java.io.Serializable {

	private String dataStream;
	private char type;

	public ItfConfigId() {
	}

	public ItfConfigId(String dataStream, char type) {
		this.dataStream = dataStream;
		this.type = type;
	}

	public String getDataStream() {
		return this.dataStream;
	}

	public void setDataStream(String dataStream) {
		this.dataStream = dataStream;
	}

	public char getType() {
		return this.type;
	}

	public void setType(char type) {
		this.type = type;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItfConfigId))
			return false;
		ItfConfigId castOther = (ItfConfigId) other;

		return ((this.getDataStream() == castOther.getDataStream()) || (this.getDataStream() != null
				&& castOther.getDataStream() != null && this.getDataStream().equals(castOther.getDataStream())))
				&& (this.getType() == castOther.getType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDataStream() == null ? 0 : this.getDataStream().hashCode());
		result = 37 * result + this.getType();
		return result;
	}

}
