// default package
// Generated 2018/4/19 ?? 06:11:16 by Hibernate Tools 3.4.0.CR1
package com.lifung.dao;
import java.util.Date;

/**
 * ItfConfig generated by hbm2java
 */
public class ItfConfig implements java.io.Serializable {

	private ItfConfigId id;
	private String descr;
	private String fileLocation;
	private String outFileLocation;
	private String logLocation;
	private String failLocation;
	private String archiveLocation;
	private String parseratLocation;
	private String preProcess;
	private String postProcess;
	private Character emailToType;
	private Integer emailTo;
	private Character emailToType2;
	private Integer emailTo2;
	private String targetDb;
	private String encodeSp;
	private String postingSp;
	private Date addDate;
	private String addWho;
	private String interfaceClass;
	private int dataSize;
	private String storerKey;
	private Date lastDtsStartDate;
	private Date lastDtsEndDate;
	private Date lastSpStartDate;
	private Date lastSpEndDate;
	private String lastFileName;
	private Integer lastRowProcessed;
	private Integer lastRetry;
	private Character activeFlag;
	private String configSp;
	private String convFileLocation;
	private String convFileArchiveLocation;
	private String language;
	private String fieldMdtcheck;
	private String selectUpdateCols;
	private String emailAttachment;
	private Integer maxLength1;
	private Integer maxLength2;
	private Integer maxLength3;
	private String cfgDefaultValue;
	private int noOfDaysPurge;
	private String lastFileNameUploaded;
	private String otherServer;
	private String otherDataBase;
	private char obsolete;
	private String srcFormat;
	private String targetFormat;
	private String lastInd;
	private Date editDate;
	private String editWho;
	private String emailEncode;

	public ItfConfig() {
	}

	public ItfConfig(ItfConfigId id, int dataSize, String language, String fieldMdtcheck, String selectUpdateCols,
			String emailAttachment, String cfgDefaultValue, int noOfDaysPurge, String lastFileNameUploaded,
			String otherServer, String otherDataBase, char obsolete, String lastInd) {
		this.id = id;
		this.dataSize = dataSize;
		this.language = language;
		this.fieldMdtcheck = fieldMdtcheck;
		this.selectUpdateCols = selectUpdateCols;
		this.emailAttachment = emailAttachment;
		this.cfgDefaultValue = cfgDefaultValue;
		this.noOfDaysPurge = noOfDaysPurge;
		this.lastFileNameUploaded = lastFileNameUploaded;
		this.otherServer = otherServer;
		this.otherDataBase = otherDataBase;
		this.obsolete = obsolete;
		this.lastInd = lastInd;
	}

	public ItfConfig(ItfConfigId id, String descr, String fileLocation, String outFileLocation, String logLocation,
			String failLocation, String archiveLocation, String parseratLocation, String preProcess, String postProcess,
			Character emailToType, Integer emailTo, Character emailToType2, Integer emailTo2, String targetDb,
			String encodeSp, String postingSp, Date addDate, String addWho, String interfaceClass, int dataSize,
			String storerKey, Date lastDtsStartDate, Date lastDtsEndDate, Date lastSpStartDate, Date lastSpEndDate,
			String lastFileName, Integer lastRowProcessed, Integer lastRetry, Character activeFlag, String configSp,
			String convFileLocation, String convFileArchiveLocation, String language, String fieldMdtcheck,
			String selectUpdateCols, String emailAttachment, Integer maxLength1, Integer maxLength2, Integer maxLength3,
			String cfgDefaultValue, int noOfDaysPurge, String lastFileNameUploaded, String otherServer,
			String otherDataBase, char obsolete, String srcFormat, String targetFormat, String lastInd, Date editDate,
			String editWho, String emailEncode) {
		this.id = id;
		this.descr = descr;
		this.fileLocation = fileLocation;
		this.outFileLocation = outFileLocation;
		this.logLocation = logLocation;
		this.failLocation = failLocation;
		this.archiveLocation = archiveLocation;
		this.parseratLocation = parseratLocation;
		this.preProcess = preProcess;
		this.postProcess = postProcess;
		this.emailToType = emailToType;
		this.emailTo = emailTo;
		this.emailToType2 = emailToType2;
		this.emailTo2 = emailTo2;
		this.targetDb = targetDb;
		this.encodeSp = encodeSp;
		this.postingSp = postingSp;
		this.addDate = addDate;
		this.addWho = addWho;
		this.interfaceClass = interfaceClass;
		this.dataSize = dataSize;
		this.storerKey = storerKey;
		this.lastDtsStartDate = lastDtsStartDate;
		this.lastDtsEndDate = lastDtsEndDate;
		this.lastSpStartDate = lastSpStartDate;
		this.lastSpEndDate = lastSpEndDate;
		this.lastFileName = lastFileName;
		this.lastRowProcessed = lastRowProcessed;
		this.lastRetry = lastRetry;
		this.activeFlag = activeFlag;
		this.configSp = configSp;
		this.convFileLocation = convFileLocation;
		this.convFileArchiveLocation = convFileArchiveLocation;
		this.language = language;
		this.fieldMdtcheck = fieldMdtcheck;
		this.selectUpdateCols = selectUpdateCols;
		this.emailAttachment = emailAttachment;
		this.maxLength1 = maxLength1;
		this.maxLength2 = maxLength2;
		this.maxLength3 = maxLength3;
		this.cfgDefaultValue = cfgDefaultValue;
		this.noOfDaysPurge = noOfDaysPurge;
		this.lastFileNameUploaded = lastFileNameUploaded;
		this.otherServer = otherServer;
		this.otherDataBase = otherDataBase;
		this.obsolete = obsolete;
		this.srcFormat = srcFormat;
		this.targetFormat = targetFormat;
		this.lastInd = lastInd;
		this.editDate = editDate;
		this.editWho = editWho;
		this.emailEncode = emailEncode;
	}

	public ItfConfigId getId() {
		return this.id;
	}

	public void setId(ItfConfigId id) {
		this.id = id;
	}

	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	public String getFileLocation() {
		return this.fileLocation;
	}

	public void setFileLocation(String fileLocation) {
		this.fileLocation = fileLocation;
	}

	public String getOutFileLocation() {
		return this.outFileLocation;
	}

	public void setOutFileLocation(String outFileLocation) {
		this.outFileLocation = outFileLocation;
	}

	public String getLogLocation() {
		return this.logLocation;
	}

	public void setLogLocation(String logLocation) {
		this.logLocation = logLocation;
	}

	public String getFailLocation() {
		return this.failLocation;
	}

	public void setFailLocation(String failLocation) {
		this.failLocation = failLocation;
	}

	public String getArchiveLocation() {
		return this.archiveLocation;
	}

	public void setArchiveLocation(String archiveLocation) {
		this.archiveLocation = archiveLocation;
	}

	public String getParseratLocation() {
		return this.parseratLocation;
	}

	public void setParseratLocation(String parseratLocation) {
		this.parseratLocation = parseratLocation;
	}

	public String getPreProcess() {
		return this.preProcess;
	}

	public void setPreProcess(String preProcess) {
		this.preProcess = preProcess;
	}

	public String getPostProcess() {
		return this.postProcess;
	}

	public void setPostProcess(String postProcess) {
		this.postProcess = postProcess;
	}

	public Character getEmailToType() {
		return this.emailToType;
	}

	public void setEmailToType(Character emailToType) {
		this.emailToType = emailToType;
	}

	public Integer getEmailTo() {
		return this.emailTo;
	}

	public void setEmailTo(Integer emailTo) {
		this.emailTo = emailTo;
	}

	public Character getEmailToType2() {
		return this.emailToType2;
	}

	public void setEmailToType2(Character emailToType2) {
		this.emailToType2 = emailToType2;
	}

	public Integer getEmailTo2() {
		return this.emailTo2;
	}

	public void setEmailTo2(Integer emailTo2) {
		this.emailTo2 = emailTo2;
	}

	public String getTargetDb() {
		return this.targetDb;
	}

	public void setTargetDb(String targetDb) {
		this.targetDb = targetDb;
	}

	public String getEncodeSp() {
		return this.encodeSp;
	}

	public void setEncodeSp(String encodeSp) {
		this.encodeSp = encodeSp;
	}

	public String getPostingSp() {
		return this.postingSp;
	}

	public void setPostingSp(String postingSp) {
		this.postingSp = postingSp;
	}

	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	public String getAddWho() {
		return this.addWho;
	}

	public void setAddWho(String addWho) {
		this.addWho = addWho;
	}

	public String getInterfaceClass() {
		return this.interfaceClass;
	}

	public void setInterfaceClass(String interfaceClass) {
		this.interfaceClass = interfaceClass;
	}

	public int getDataSize() {
		return this.dataSize;
	}

	public void setDataSize(int dataSize) {
		this.dataSize = dataSize;
	}

	public String getStorerKey() {
		return this.storerKey;
	}

	public void setStorerKey(String storerKey) {
		this.storerKey = storerKey;
	}

	public Date getLastDtsStartDate() {
		return this.lastDtsStartDate;
	}

	public void setLastDtsStartDate(Date lastDtsStartDate) {
		this.lastDtsStartDate = lastDtsStartDate;
	}

	public Date getLastDtsEndDate() {
		return this.lastDtsEndDate;
	}

	public void setLastDtsEndDate(Date lastDtsEndDate) {
		this.lastDtsEndDate = lastDtsEndDate;
	}

	public Date getLastSpStartDate() {
		return this.lastSpStartDate;
	}

	public void setLastSpStartDate(Date lastSpStartDate) {
		this.lastSpStartDate = lastSpStartDate;
	}

	public Date getLastSpEndDate() {
		return this.lastSpEndDate;
	}

	public void setLastSpEndDate(Date lastSpEndDate) {
		this.lastSpEndDate = lastSpEndDate;
	}

	public String getLastFileName() {
		return this.lastFileName;
	}

	public void setLastFileName(String lastFileName) {
		this.lastFileName = lastFileName;
	}

	public Integer getLastRowProcessed() {
		return this.lastRowProcessed;
	}

	public void setLastRowProcessed(Integer lastRowProcessed) {
		this.lastRowProcessed = lastRowProcessed;
	}

	public Integer getLastRetry() {
		return this.lastRetry;
	}

	public void setLastRetry(Integer lastRetry) {
		this.lastRetry = lastRetry;
	}

	public Character getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Character activeFlag) {
		this.activeFlag = activeFlag;
	}

	public String getConfigSp() {
		return this.configSp;
	}

	public void setConfigSp(String configSp) {
		this.configSp = configSp;
	}

	public String getConvFileLocation() {
		return this.convFileLocation;
	}

	public void setConvFileLocation(String convFileLocation) {
		this.convFileLocation = convFileLocation;
	}

	public String getConvFileArchiveLocation() {
		return this.convFileArchiveLocation;
	}

	public void setConvFileArchiveLocation(String convFileArchiveLocation) {
		this.convFileArchiveLocation = convFileArchiveLocation;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getFieldMdtcheck() {
		return this.fieldMdtcheck;
	}

	public void setFieldMdtcheck(String fieldMdtcheck) {
		this.fieldMdtcheck = fieldMdtcheck;
	}

	public String getSelectUpdateCols() {
		return this.selectUpdateCols;
	}

	public void setSelectUpdateCols(String selectUpdateCols) {
		this.selectUpdateCols = selectUpdateCols;
	}

	public String getEmailAttachment() {
		return this.emailAttachment;
	}

	public void setEmailAttachment(String emailAttachment) {
		this.emailAttachment = emailAttachment;
	}

	public Integer getMaxLength1() {
		return this.maxLength1;
	}

	public void setMaxLength1(Integer maxLength1) {
		this.maxLength1 = maxLength1;
	}

	public Integer getMaxLength2() {
		return this.maxLength2;
	}

	public void setMaxLength2(Integer maxLength2) {
		this.maxLength2 = maxLength2;
	}

	public Integer getMaxLength3() {
		return this.maxLength3;
	}

	public void setMaxLength3(Integer maxLength3) {
		this.maxLength3 = maxLength3;
	}

	public String getCfgDefaultValue() {
		return this.cfgDefaultValue;
	}

	public void setCfgDefaultValue(String cfgDefaultValue) {
		this.cfgDefaultValue = cfgDefaultValue;
	}

	public int getNoOfDaysPurge() {
		return this.noOfDaysPurge;
	}

	public void setNoOfDaysPurge(int noOfDaysPurge) {
		this.noOfDaysPurge = noOfDaysPurge;
	}

	public String getLastFileNameUploaded() {
		return this.lastFileNameUploaded;
	}

	public void setLastFileNameUploaded(String lastFileNameUploaded) {
		this.lastFileNameUploaded = lastFileNameUploaded;
	}

	public String getOtherServer() {
		return this.otherServer;
	}

	public void setOtherServer(String otherServer) {
		this.otherServer = otherServer;
	}

	public String getOtherDataBase() {
		return this.otherDataBase;
	}

	public void setOtherDataBase(String otherDataBase) {
		this.otherDataBase = otherDataBase;
	}

	public char getObsolete() {
		return this.obsolete;
	}

	public void setObsolete(char obsolete) {
		this.obsolete = obsolete;
	}

	public String getSrcFormat() {
		return this.srcFormat;
	}

	public void setSrcFormat(String srcFormat) {
		this.srcFormat = srcFormat;
	}

	public String getTargetFormat() {
		return this.targetFormat;
	}

	public void setTargetFormat(String targetFormat) {
		this.targetFormat = targetFormat;
	}

	public String getLastInd() {
		return this.lastInd;
	}

	public void setLastInd(String lastInd) {
		this.lastInd = lastInd;
	}

	public Date getEditDate() {
		return this.editDate;
	}

	public void setEditDate(Date editDate) {
		this.editDate = editDate;
	}

	public String getEditWho() {
		return this.editWho;
	}

	public void setEditWho(String editWho) {
		this.editWho = editWho;
	}

	public String getEmailEncode() {
		return this.emailEncode;
	}

	public void setEmailEncode(String emailEncode) {
		this.emailEncode = emailEncode;
	}

}
