// default package
// Generated 2018/12/5 ?? 02:48:01 by Hibernate Tools 3.4.0.CR1
package com.lifung.dao;
/**
 * OutLineId generated by hbm2java
 */
public class OutLineId implements java.io.Serializable {

	private int fileKey;
	private int seqNo;

	public OutLineId() {
	}

	public OutLineId(int fileKey, int seqNo) {
		this.fileKey = fileKey;
		this.seqNo = seqNo;
	}

	public int getFileKey() {
		return this.fileKey;
	}

	public void setFileKey(int fileKey) {
		this.fileKey = fileKey;
	}

	public int getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(int seqNo) {
		this.seqNo = seqNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OutLineId))
			return false;
		OutLineId castOther = (OutLineId) other;

		return (this.getFileKey() == castOther.getFileKey()) && (this.getSeqNo() == castOther.getSeqNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFileKey();
		result = 37 * result + this.getSeqNo();
		return result;
	}

}
