// default package
// Generated 2018/12/5 ?? 02:48:01 by Hibernate Tools 3.4.0.CR1
package com.lifung.dao;
import java.util.Date;

/**
 * OutLine generated by hbm2java
 */
public class OutLine implements java.io.Serializable {

	private OutLineId id;
	private String dataStream;
	private Integer attachmentId;
	private String fileName;
	private char status;
	private String lineText;
	private String errMsg;
	private Date addDate;
	private Date editDate;
	private String sourceKey;
	private String editWho;
	private String lineTextUnicode;
	private String archiveCop;
	private String trafficCop;

	public OutLine() {
	}

	public OutLine(OutLineId id, String dataStream, char status, Date addDate, Date editDate) {
		this.id = id;
		this.dataStream = dataStream;
		this.status = status;
		this.addDate = addDate;
		this.editDate = editDate;
	}

	public OutLine(OutLineId id, String dataStream, Integer attachmentId, String fileName, char status, String lineText,
			String errMsg, Date addDate, Date editDate, String sourceKey, String editWho, String lineTextUnicode,
			String archiveCop, String trafficCop) {
		this.id = id;
		this.dataStream = dataStream;
		this.attachmentId = attachmentId;
		this.fileName = fileName;
		this.status = status;
		this.lineText = lineText;
		this.errMsg = errMsg;
		this.addDate = addDate;
		this.editDate = editDate;
		this.sourceKey = sourceKey;
		this.editWho = editWho;
		this.lineTextUnicode = lineTextUnicode;
		this.archiveCop = archiveCop;
		this.trafficCop = trafficCop;
	}

	public OutLineId getId() {
		return this.id;
	}

	public void setId(OutLineId id) {
		this.id = id;
	}

	public String getDataStream() {
		return this.dataStream;
	}

	public void setDataStream(String dataStream) {
		this.dataStream = dataStream;
	}

	public Integer getAttachmentId() {
		return this.attachmentId;
	}

	public void setAttachmentId(Integer attachmentId) {
		this.attachmentId = attachmentId;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	public String getLineText() {
		return this.lineText;
	}

	public void setLineText(String lineText) {
		this.lineText = lineText;
	}

	public String getErrMsg() {
		return this.errMsg;
	}

	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;
	}

	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	public Date getEditDate() {
		return this.editDate;
	}

	public void setEditDate(Date editDate) {
		this.editDate = editDate;
	}

	public String getSourceKey() {
		return this.sourceKey;
	}

	public void setSourceKey(String sourceKey) {
		this.sourceKey = sourceKey;
	}

	public String getEditWho() {
		return this.editWho;
	}

	public void setEditWho(String editWho) {
		this.editWho = editWho;
	}

	public String getLineTextUnicode() {
		return this.lineTextUnicode;
	}

	public void setLineTextUnicode(String lineTextUnicode) {
		this.lineTextUnicode = lineTextUnicode;
	}

	public String getArchiveCop() {
		return this.archiveCop;
	}

	public void setArchiveCop(String archiveCop) {
		this.archiveCop = archiveCop;
	}

	public String getTrafficCop() {
		return this.trafficCop;
	}

	public void setTrafficCop(String trafficCop) {
		this.trafficCop = trafficCop;
	}

}
