// default package
// Generated 2018/11/29 ?? 03:38:52 by Hibernate Tools 3.4.0.CR1
package com.lifung.dao;
import java.util.Date;

/**
 * PmaRtnQty generated by hbm2java
 */
public class PmaRtnQty implements java.io.Serializable {

	private String carrierReference;
	private Long qtyExpected;
	private Date createDateTime;
	private String ipAddress;

	public PmaRtnQty() {
	}

	public PmaRtnQty(String carrierReference) {
		this.carrierReference = carrierReference;
	}

	public PmaRtnQty(String carrierReference, Long qtyExpected, Date createDateTime, String ipAddress) {
		this.carrierReference = carrierReference;
		this.qtyExpected = qtyExpected;
		this.createDateTime = createDateTime;
		this.ipAddress = ipAddress;
	}

	public String getCarrierReference() {
		return this.carrierReference;
	}

	public void setCarrierReference(String carrierReference) {
		this.carrierReference = carrierReference;
	}

	public Long getQtyExpected() {
		return this.qtyExpected;
	}

	public void setQtyExpected(Long qtyExpected) {
		this.qtyExpected = qtyExpected;
	}

	public Date getCreateDateTime() {
		return this.createDateTime;
	}

	public void setCreateDateTime(Date createDateTime) {
		this.createDateTime = createDateTime;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

}
