package com.lifung.dao;
import java.util.Date;

/**
 * Rdtprinter generated by hbm2java
 */
public class Rdtprinter implements java.io.Serializable {

	private String printerId;
	private String description;
	private String winPrinter;
	private Date addDate;
	private String addWho;
	private Date editDate;
	private String editWho;
	private String printerGroup;
	private Integer voicePrinterNo;
	private String spoolerGroup;

	public Rdtprinter() {
	}

	public Rdtprinter(String printerId, String description, String winPrinter, String addWho, String spoolerGroup) {
		this.printerId = printerId;
		this.description = description;
		this.winPrinter = winPrinter;
		this.addWho = addWho;
		this.spoolerGroup = spoolerGroup;
	}

	public Rdtprinter(String printerId, String description, String winPrinter, Date addDate, String addWho,
			Date editDate, String editWho, String printerGroup, Integer voicePrinterNo, String spoolerGroup) {
		this.printerId = printerId;
		this.description = description;
		this.winPrinter = winPrinter;
		this.addDate = addDate;
		this.addWho = addWho;
		this.editDate = editDate;
		this.editWho = editWho;
		this.printerGroup = printerGroup;
		this.voicePrinterNo = voicePrinterNo;
		this.spoolerGroup = spoolerGroup;
	}

	public String getPrinterId() {
		return this.printerId;
	}

	public void setPrinterId(String printerId) {
		this.printerId = printerId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getWinPrinter() {
		return this.winPrinter;
	}

	public void setWinPrinter(String winPrinter) {
		this.winPrinter = winPrinter;
	}

	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	public String getAddWho() {
		return this.addWho;
	}

	public void setAddWho(String addWho) {
		this.addWho = addWho;
	}

	public Date getEditDate() {
		return this.editDate;
	}

	public void setEditDate(Date editDate) {
		this.editDate = editDate;
	}

	public String getEditWho() {
		return this.editWho;
	}

	public void setEditWho(String editWho) {
		this.editWho = editWho;
	}

	public String getPrinterGroup() {
		return this.printerGroup;
	}

	public void setPrinterGroup(String printerGroup) {
		this.printerGroup = printerGroup;
	}

	public Integer getVoicePrinterNo() {
		return this.voicePrinterNo;
	}

	public void setVoicePrinterNo(Integer voicePrinterNo) {
		this.voicePrinterNo = voicePrinterNo;
	}

	public String getSpoolerGroup() {
		return this.spoolerGroup;
	}

	public void setSpoolerGroup(String spoolerGroup) {
		this.spoolerGroup = spoolerGroup;
	}

}
