// default package
// Generated 2018/12/27 ?? 04:04:58 by Hibernate Tools 3.4.0.CR1
package com.lifung.dao;
import java.util.Date;

/**
 * Transmitlog2 generated by hbm2java
 */
public class Transmitlog2 implements java.io.Serializable {

	private String transmitlogkey;
	private String tablename;
	private String key1;
	private String key2;
	private String key3;
	private String transmitflag;
	private String transmitbatch;
	private Date addDate;
	private String addWho;
	private Date editDate;
	private String editWho;
	private String trafficCop;
	private String archiveCop;

	public Transmitlog2() {
	}

	public Transmitlog2(String transmitlogkey, String tablename, String key1, String key3, String transmitflag,
			Date addDate, String addWho, Date editDate, String editWho) {
		this.transmitlogkey = transmitlogkey;
		this.tablename = tablename;
		this.key1 = key1;
		this.key3 = key3;
		this.transmitflag = transmitflag;
		this.addDate = addDate;
		this.addWho = addWho;
		this.editDate = editDate;
		this.editWho = editWho;
	}

	public Transmitlog2(String transmitlogkey, String tablename, String key1, String key2, String key3,
			String transmitflag, String transmitbatch, Date addDate, String addWho, Date editDate, String editWho,
			String trafficCop, String archiveCop) {
		this.transmitlogkey = transmitlogkey;
		this.tablename = tablename;
		this.key1 = key1;
		this.key2 = key2;
		this.key3 = key3;
		this.transmitflag = transmitflag;
		this.transmitbatch = transmitbatch;
		this.addDate = addDate;
		this.addWho = addWho;
		this.editDate = editDate;
		this.editWho = editWho;
		this.trafficCop = trafficCop;
		this.archiveCop = archiveCop;
	}

	public String getTransmitlogkey() {
		return this.transmitlogkey;
	}

	public void setTransmitlogkey(String transmitlogkey) {
		this.transmitlogkey = transmitlogkey;
	}

	public String getTablename() {
		return this.tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	public String getKey1() {
		return this.key1;
	}

	public void setKey1(String key1) {
		this.key1 = key1;
	}

	public String getKey2() {
		return this.key2;
	}

	public void setKey2(String key2) {
		this.key2 = key2;
	}

	public String getKey3() {
		return this.key3;
	}

	public void setKey3(String key3) {
		this.key3 = key3;
	}

	public String getTransmitflag() {
		return this.transmitflag;
	}

	public void setTransmitflag(String transmitflag) {
		this.transmitflag = transmitflag;
	}

	public String getTransmitbatch() {
		return this.transmitbatch;
	}

	public void setTransmitbatch(String transmitbatch) {
		this.transmitbatch = transmitbatch;
	}

	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	public String getAddWho() {
		return this.addWho;
	}

	public void setAddWho(String addWho) {
		this.addWho = addWho;
	}

	public Date getEditDate() {
		return this.editDate;
	}

	public void setEditDate(Date editDate) {
		this.editDate = editDate;
	}

	public String getEditWho() {
		return this.editWho;
	}

	public void setEditWho(String editWho) {
		this.editWho = editWho;
	}

	public String getTrafficCop() {
		return this.trafficCop;
	}

	public void setTrafficCop(String trafficCop) {
		this.trafficCop = trafficCop;
	}

	public String getArchiveCop() {
		return this.archiveCop;
	}

	public void setArchiveCop(String archiveCop) {
		this.archiveCop = archiveCop;
	}

}
